"use strict";
"require view";
"require dom";
"require poll";
"require rpc";
"require network";
// WARN: generated by rsbuild - do not edit

// The require scope
var __webpack_require__ = {};

// webpack/runtime/define_property_getters
(() => {
__webpack_require__.d = (exports, getters, values) => {
	var define = (defs, kind) => {
		for(var key in defs) {
			if(__webpack_require__.o(defs, key) && !__webpack_require__.o(exports, key)) {
				Object.defineProperty(exports, key, { enumerable: true, [kind]: defs[key] });
			}
		}
	};
	define(getters, "get");
	define(values, "value");
};
})();
// webpack/runtime/has_own_property
(() => {
__webpack_require__.o = (obj, prop) => (Object.prototype.hasOwnProperty.call(obj, prop))
})();
// webpack/runtime/make_namespace_object
(() => {
// define __esModule on exports
__webpack_require__.r = (exports) => {
	if(typeof Symbol !== 'undefined' && Symbol.toStringTag) {
		Object.defineProperty(exports, Symbol.toStringTag, { value: 'Module' });
	}
	Object.defineProperty(exports, '__esModule', { value: true });
};
})();
var __webpack_exports__ = {};
// ESM COMPAT FLAG
__webpack_require__.r(__webpack_exports__);

// EXPORTS
__webpack_require__.d(__webpack_exports__, {
  main: () => (/* binding */ main)
});

;// CONCATENATED MODULE: ./web/fluentdashboard/model.ts
function model_t(t) {
    return null === t || "object" != typeof t || Array.isArray(t) ? {} : t;
}
function model_e(t) {
    return "string" == typeof t ? t : "";
}
function model_r(t) {
    return "number" == typeof t && Number.isFinite(t) ? t : 0;
}
function model_o(e, i = "free") {
    let n = model_t(e);
    return {
        total: model_r(n.total),
        free: model_r(n[i] ?? n.free)
    };
}
function normalizeSystemSnapshot(i, n, a) {
    let l = model_t(i), m = model_t(n), u = model_t(l.release), f = model_t(a), s = Array.isArray(m.load) ? m.load.map(model_r) : [];
    return {
        hostname: model_e(l.hostname),
        model: model_e(l.model),
        architecture: model_e(l.system),
        target: model_e(u.target),
        firmware: model_e(u.description),
        kernel: model_e(l.kernel),
        luciVersion: [
            model_e(f.branch),
            model_e(f.revision)
        ].filter(Boolean).join(" "),
        uptime: model_r(m.uptime),
        localtime: model_r(m.localtime),
        load: s,
        memory: model_o(m.memory, "available"),
        swap: model_o(m.swap),
        root: model_o(m.root),
        tmp: model_o(m.tmp)
    };
}
function usedPercent(t) {
    return t.total <= 0 ? 0 : Math.min(100, Math.max(0, (t.total - t.free) / t.total * 100));
}
function formatBytes(t) {
    if (!Number.isFinite(t) || t <= 0) return "0 B";
    let e = [
        "B",
        "KiB",
        "MiB",
        "GiB",
        "TiB"
    ], r = Math.min(Math.floor(Math.log(t) / Math.log(1024)), e.length - 1), o = t / 1024 ** r;
    return `${o >= 10 || 0 === r ? o.toFixed(0) : o.toFixed(1)} ${e[r]}`;
}
function formatDuration(t) {
    if (!Number.isFinite(t) || t <= 0) return "-";
    let e = Math.floor(t / 86400), r = Math.floor(t % 86400 / 3600), o = Math.floor(t % 3600 / 60);
    return [
        e > 0 ? `${e}d` : "",
        `${r}h`,
        `${o}m`
    ].filter(Boolean).join(" ");
}
function formatLoad(t) {
    return 0 === t.length ? "-" : t.slice(0, 3).map((t)=>(t / 65535).toFixed(2)).join(" / ");
}
function formatLocalTime(t) {
    return !Number.isFinite(t) || t <= 0 ? "-" : new Intl.DateTimeFormat(void 0, {
        dateStyle: "medium",
        timeStyle: "medium",
        timeZone: "UTC"
    }).format(new Date(1000 * t));
}

;// CONCATENATED MODULE: ./web/fluentdashboard/index.tsx

let fluentdashboard_i = rpc.declare({
    object: "system",
    method: "board"
}), fluentdashboard_o = rpc.declare({
    object: "system",
    method: "info"
}), d = rpc.declare({
    object: "luci",
    method: "getVersion"
}), fluentdashboard_l = rpc.declare({
    object: "luci-rpc",
    method: "getDHCPLeases",
    expect: {
        "": {}
    }
});
function fluentdashboard_c(e) {
    return null === e || "object" != typeof e || Array.isArray(e) ? {} : e;
}
function fluentdashboard_u(e) {
    return "string" == typeof e ? e : "";
}
function fluentdashboard_m(e) {
    return "number" == typeof e && Number.isFinite(e) ? e : 0;
}
async function p(e, t) {
    try {
        return await e;
    } catch  {
        return t;
    }
}
function fluentdashboard_f(e, t = !1) {
    let a = e.getL3Device() ?? e.getDevice();
    return {
        name: e.getName(),
        protocol: e.getI18n(),
        up: e.isUp(),
        addresses: t ? e.getIP6Addrs() : e.getIPAddrs(),
        gateway: t ? e.getGateway6Addr() : e.getGatewayAddr(),
        uptime: e.getUptime(),
        device: a?.getName() ?? "",
        rx: a?.getRXBytes() ?? 0,
        tx: a?.getTXBytes() ?? 0
    };
}
async function h() {
    await p(network.flushCache(), {});
    let [e, t, a, r, n, l, c, u] = await Promise.all([
        p(fluentdashboard_i(), {}),
        p(fluentdashboard_o(), {}),
        p(d(), {}),
        p(network.getWANNetworks(), []),
        p(network.getWAN6Networks(), []),
        p(network.getNetworks(), []),
        p(network.getWifiDevices(), []),
        p(network.getWifiNetworks(), [])
    ]), m = u.map((e)=>{
        let t = c.find((t)=>t.getName() === e.getWifiDeviceName());
        return {
            radio: t?.getName() ?? e.getWifiDeviceName() ?? "",
            hardware: t?.getI18n() ?? "",
            up: e.isUp() && !t?.isDisabled(),
            ssid: e.getActiveSSID() || e.getSSID() || e.getMeshID() || "",
            mode: e.getActiveModeI18n() || e.getMode(),
            channel: e.getChannel(),
            frequency: e.getFrequency() ?? "",
            encryption: e.getActiveEncryption()
        };
    });
    for (let e of c)m.some((t)=>t.radio === e.getName()) || m.push({
        radio: e.getName(),
        hardware: e.getI18n(),
        up: e.isUp() && !e.isDisabled(),
        ssid: "",
        mode: "",
        channel: null,
        frequency: "",
        encryption: ""
    });
    return {
        system: normalizeSystemSnapshot(e, t, a),
        wan4: r.map((e)=>fluentdashboard_f(e)),
        wan6: n.map((e)=>fluentdashboard_f(e, !0)),
        interfaces: l.filter((e)=>"loopback" !== e.getName()).map((e)=>fluentdashboard_f(e)),
        wireless: m,
        updatedAt: new Date()
    };
}
async function y() {
    let [e, t, a] = await Promise.all([
        p(fluentdashboard_l(), {}),
        p(network.getWifiNetworks(), []),
        p(network.getHostHints(), null)
    ]), r = await Promise.all(t.map(async (e)=>({
            wifi: e,
            peers: await p(e.getAssocList(), [])
        }))), s = [];
    for (let { wifi: e, peers: t } of r)for (let r of t){
        let t = a?.getHostnameByMACAddr(r.mac) || a?.getIPAddrByMACAddr(r.mac) || a?.getIP6AddrByMACAddr(r.mac) || "";
        s.push({
            network: e.getActiveSSID() || e.getSSID() || e.getName(),
            hostname: t,
            mac: r.mac,
            signal: r.signal,
            noise: r.noise ?? null,
            rxRate: r.rx?.rate ?? 0,
            txRate: r.tx?.rate ?? 0
        });
    }
    return {
        leases: function(e) {
            let t = fluentdashboard_c(e), a = [];
            if (Array.isArray(t.dhcp_leases)) for (let e of t.dhcp_leases){
                let t = fluentdashboard_c(e);
                a.push({
                    family: "IPv4",
                    hostname: fluentdashboard_u(t.hostname),
                    address: fluentdashboard_u(t.ipaddr),
                    identifier: fluentdashboard_u(t.macaddr),
                    expires: !1 !== t.expires && fluentdashboard_m(t.expires)
                });
            }
            if (Array.isArray(t.dhcp6_leases)) for (let e of t.dhcp6_leases){
                let t = fluentdashboard_c(e), r = Array.isArray(t.ip6addrs) ? t.ip6addrs.filter((e)=>"string" == typeof e) : [];
                a.push({
                    family: "IPv6",
                    hostname: fluentdashboard_u(t.hostname),
                    address: r.join(", ") || fluentdashboard_u(t.ip6addr),
                    identifier: fluentdashboard_u(t.duid),
                    expires: !1 !== t.expires && fluentdashboard_m(t.expires)
                });
            }
            return a;
        }(e),
        clients: s
    };
}
function g(e) {
    return null == e || "" === e ? "-" : String(e);
}
function w(e) {
    return E("span", {
        class: `fluent-dashboard__status fluent-dashboard__status--${e ? "up" : "down"}`
    }, e ? _("Online") : _("Offline"));
}
function b(e, t, a, r = !1) {
    return E("section", {
        class: `fluent-dashboard__card${r ? " fluent-dashboard__card--wide" : ""}`,
        "data-dashboard-section": e
    }, [
        E("h2", {
            class: "fluent-dashboard__card-title"
        }, t),
        E("div", {
            class: "fluent-dashboard__card-content"
        }, a)
    ]);
}
function v(e, t, a) {
    let r = t.length ? t.map((e)=>E("tr", {}, e.map((e)=>E("td", {}, e instanceof Node ? e : g(e))))) : [
        E("tr", {}, E("td", {
            class: "fluent-dashboard__empty",
            colspan: e.length
        }, a))
    ];
    return E("div", {
        class: "fluent-dashboard__table-wrap"
    }, E("table", {
        class: "fluent-dashboard__table"
    }, [
        E("thead", {}, E("tr", {}, e.map((e)=>E("th", {}, e)))),
        E("tbody", {}, r)
    ]));
}
function A(e) {
    return b("system", _("System"), E("dl", {
        class: "fluent-dashboard__details"
    }, [
        [
            _("Hostname"),
            e.hostname
        ],
        [
            _("Model"),
            e.model
        ],
        [
            _("Architecture"),
            e.architecture
        ],
        [
            _("Target Platform"),
            e.target
        ],
        [
            _("Firmware Version"),
            e.firmware
        ],
        [
            _("Kernel Version"),
            e.kernel
        ],
        [
            _("LuCI Version"),
            e.luciVersion
        ],
        [
            _("Local Time"),
            formatLocalTime(e.localtime)
        ],
        [
            _("Uptime"),
            formatDuration(e.uptime)
        ],
        [
            _("Load Average"),
            formatLoad(e.load)
        ]
    ].flatMap(([e, t])=>[
            E("dt", {}, e),
            E("dd", {}, t instanceof Node ? t : g(t))
        ])));
}
function S(t) {
    let a = [
        [
            _("Memory"),
            t.memory
        ],
        [
            _("Swap"),
            t.swap
        ],
        [
            _("Root storage"),
            t.root
        ],
        [
            _("Temporary storage"),
            t.tmp
        ]
    ];
    return b("resources", _("Resources"), a.map(([t, a])=>{
        let r, s;
        return r = Math.max(0, a.total - a.free), s = usedPercent(a), E("div", {
            class: "fluent-dashboard__meter"
        }, [
            E("div", {
                class: "fluent-dashboard__meter-label"
            }, [
                E("span", {}, t),
                E("span", {}, `${formatBytes(r)} / ${formatBytes(a.total)}`)
            ]),
            E("div", {
                class: "fluent-dashboard__meter-track",
                role: "progressbar",
                "aria-valuemin": 0,
                "aria-valuemax": 100,
                "aria-valuenow": Math.round(s)
            }, E("span", {
                class: "fluent-dashboard__meter-value",
                style: `width:${s.toFixed(1)}%`
            }))
        ]);
    }));
}
function x(e) {
    let a = [
        ...e.wan4.map((e)=>[
                "IPv4",
                e
            ]),
        ...e.wan6.map((e)=>[
                "IPv6",
                e
            ])
    ];
    return b("internet", _("Internet"), v([
        _("Family"),
        _("Interface"),
        _("Status"),
        _("Protocol"),
        _("Address"),
        _("Gateway"),
        _("Uptime")
    ], a.map(([e, a])=>[
            e,
            a.name,
            w(a.up),
            a.protocol,
            a.addresses.join(", "),
            a.gateway,
            formatDuration(a.uptime)
        ]), _("No Internet connection information is available.")), !0);
}
function I(t) {
    return b("interfaces", _("Interfaces"), v([
        _("Interface"),
        _("Device"),
        _("Status"),
        _("Address"),
        _("Received"),
        _("Transmitted")
    ], t.map((t)=>[
            t.name,
            t.device,
            w(t.up),
            t.addresses.join(", "),
            formatBytes(t.rx),
            formatBytes(t.tx)
        ]), _("No network interfaces were found.")), !0);
}
function N(e) {
    return b("wireless", _("Wireless"), v([
        _("Radio"),
        _("SSID"),
        _("Status"),
        _("Mode"),
        _("Channel"),
        _("Encryption")
    ], e.map((e)=>[
            E("span", {
                title: e.hardware
            }, g(e.radio)),
            e.ssid,
            w(e.up),
            e.mode,
            null === e.channel ? "-" : e.frequency ? `${e.channel} (${e.frequency} GHz)` : e.channel,
            e.encryption
        ]), _("No wireless radios were found.")), !0);
}
function D(e) {
    return b("leases", _("Active DHCP Leases"), v([
        _("Family"),
        _("Hostname"),
        _("Address"),
        _("MAC / DUID"),
        _("Expires")
    ], e.map((e)=>{
        var a;
        return [
            e.family,
            e.hostname,
            e.address,
            e.identifier,
            !1 === (a = e.expires) ? _("Unlimited") : a <= 0 ? _("Expired") : formatDuration(a)
        ];
    }), _("There are no active DHCP leases.")), !0);
}
function k(e) {
    return e > 0 ? `${(e / 1000).toFixed(1)} ${_("Mbit/s")}` : "-";
}
function C(e) {
    return b("clients", _("Wireless Clients"), v([
        _("Network"),
        _("Host"),
        _("MAC address"),
        _("Signal"),
        _("RX / TX Rate")
    ], e.map((e)=>[
            e.network,
            e.hostname,
            e.mac,
            null === e.noise ? `${e.signal} dBm` : `${e.signal} / ${e.noise} dBm`,
            `${k(e.rxRate)} / ${k(e.txRate)}`
        ]), _("No wireless clients are connected.")), !0);
}
class P extends L.view {
    handleSave = null;
    handleSaveApply = null;
    handleReset = null;
    root = null;
    load() {
        return Promise.all([
            h(),
            y()
        ]);
    }
    replaceSection(e, t) {
        this.root?.querySelector(`[data-dashboard-section="${e}"]`)?.replaceWith(t);
    }
    async refreshSummary() {
        if (!this.root?.isConnected) return;
        let e = await h();
        if (!this.root?.isConnected) return;
        this.replaceSection("system", A(e.system)), this.replaceSection("resources", S(e.system)), this.replaceSection("internet", x(e)), this.replaceSection("interfaces", I(e.interfaces)), this.replaceSection("wireless", N(e.wireless));
        let t = this.root.querySelector("[data-dashboard-updated]");
        t && (t.textContent = e.updatedAt.toLocaleTimeString());
    }
    async refreshDetails() {
        if (!this.root?.isConnected) return;
        let e = await y();
        this.root?.isConnected && (this.replaceSection("leases", D(e.leases)), this.replaceSection("clients", C(e.clients)));
    }
    render([e, t]) {
        return document.getElementById("fluent-dashboard-styles") || document.head.appendChild(E("link", {
            id: "fluent-dashboard-styles",
            rel: "stylesheet",
            href: L.resource("view/fluentdashboard/index.css")
        })), this.root = E("div", {
            class: "fluent-dashboard"
        }, [
            E("header", {
                class: "fluent-dashboard__header"
            }, [
                E("div", {}, [
                    E("h1", {}, _("FortiGate Dashboard")),
                    E("p", {}, _("A live overview of this OpenWrt device."))
                ]),
                E("p", {
                    class: "fluent-dashboard__updated"
                }, [
                    _("Updated"),
                    " ",
                    E("time", {
                        "data-dashboard-updated": ""
                    }, e.updatedAt.toLocaleTimeString())
                ])
            ]),
            E("div", {
                class: "fluent-dashboard__grid"
            }, [
                A(e.system),
                S(e.system),
                x(e),
                I(e.interfaces),
                N(e.wireless),
                D(t.leases),
                C(t.clients)
            ])
        ]), poll.add(()=>this.refreshSummary(), 5), poll.add(()=>this.refreshDetails(), 15), this.root;
    }
}
const main = P;


return main;