export const FLUENT_DEFAULTS = {
  mode: "auto",
  primary: "#f4511e",
  dark_primary: "#ff7043",
  progressbar_font: "#3d170c",
  dark_progressbar_font: "#d6d9e5",
  page_bg: "#fafafa",
  card_bg: "#ffffff",
  sidebar_bg: "#f3f3f3",
  dark_page_bg: "#1b1b1b",
  dark_card_bg: "#2d2d2d",
  dark_sidebar_bg: "#1f1f1f",
  font_weight: "normal",
  font_size: "14",
  border_radius: "4",
  control_height: "32",
  sidebar_width: "260",
  header_height: "48",
  login_bg: "microsoft",
  blur: "40",
  transparency: "0.8",
  blur_dark: "20",
  transparency_dark: "0.8",
  card_shadow: "small",
  transition_speed: "normal",
  custom_css: "",
  custom_select: "1",
  view_transition: "1",
  tab_animation: "1",
  prefers_reduced_motion: "1",
  loading_bar: "1",
  uci_changes_preview: "1",
  direction_mode: "auto",
  progressbar_text_position: "top-start",
} as const;

export const fluentFlagDefault = (value: string): boolean => value === "1";
